
SELECT 
---FROM RAW ORDERS 
O.ORDERID,
O.ORDERDATE,
O.SHIPDATE,
O.SHIPMODE,
O.ORDERCOSTPRICE,
O.ORDERSELLINGPRICE,
ORDERCOSTPRICE-ORDERSELLINGPRICE AS ORDERPROFIT, 
--- FROM RAW CUSTOMERS
C.CUSTOMERNAME,
C.SEGMENT,
C.COUNTRY,
----FROM RAW PRODUCTS
P.PRODUCTID,
P.CATEGORY,
P.PRODUCTNAME,
P.SUBCATEGORY
FROM 
{{ ref('raw_orders') }} O
LEFT OUTER JOIN {{ ref('raw_customer') }} C 
ON O.CUSTOMERID=C.CUSTOMERID
LEFT OUTER JOIN {{ ref('raw_product') }} P 
ON O.PRODUCTID=P.PRODUCTID