SELECT 
    PRODUCTNAME,
    CATEGORY,
    SUBCATEGORY,
    SUM(ORDERPROFIT) AS PROFIT
FROM {{ ref('stg_orders') }}
GROUP BY  
PRODUCTNAME,
CATEGORY,
SUBCATEGORY
ORDER BY 
PRODUCTNAME,
CATEGORY,
SUBCATEGORY 